name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Replace credentials in settings.xml
        run: |
          sed -i "s|\${{ secrets.USERNAME }}|${{ secrets.USERNAME }}|g" settings.xml
          sed -i "s|\${{ secrets.PASSWORD }}|${{ secrets.PASSWORD }}|g" settings.xml

      - name: Replace the correct IP in pom.xml
        run: sed -i "s|localhost|10.1.10.154|g" pom.xml
  
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: joda-repo
          server-username: ${{ secrets.USERNAME }}
          server-password: ${{ secrets.PASSWORD }}

      - name: Deploy
        run: mvn --batch-mode deploy --settings settings.xml